Yojin 10 : Item, ID 기능 구현
linenive/GameProgrammingProject pull request #69
Opened 2021-12-03 06:26 UTC by chamomy127

Item Domain
1. BuildItem : Item
BuildItem은 Item을 상속받는 클래스, 가구까지는 아니지만 있어야 하는 아이템이 있을까봐 가구 전에 중간 단계를 하나 넣었음 (ex 창문)
후에 레이어 등의 변수를 가질 수 있을거라 생각함... (컵 등은 탁자같은 가구의 위에만 생성 가능 이런식으로..)

2. FurnitureItem : BuildItem
가구 아이템, 가구의 등급인 grade를 가지고 있음 (후에 이 grade정보들을 모아서 방문한 손님의 만족도나 거주민들의 행복도 등에 영향을 끼칠거라 생각함)

3. DisplayStandItem : FurnitureItem
전시대로 사용되는 아이템, Item 슬롯을 가지고 있어 그곳에 아이템을 전시함
무기전시대, 방어구 전시대, 물약 전시대 등

- functions
bool IsFullSlot() 
슬롯이 가득 차있는지 리턴
bool CanDisplayItemByIndex(int slot index)
해당 슬롯에 아이템을 넣을 수 있는지 확인
Item* SetSlotItem(Item* new item, int slot index)
해당 slot index에 원래 아이템이 있었다면, 들어있던 아이템을 반환하고 새 아이템을 집어넣음
Item* PopSlotItem(Item* new item, int slot index)
해당 슬롯이 비어있지 않다면 그곳의 아이템을 pop함
bool HasItem(string item_name) / bool HasItem(int item_id)
이 전시대에 item_name의 이름을 가졌거나, item_id의 아이템이 있는지 확인 

4. OccupiedFurnitureItem : FurnitureItem
특정 캐릭터가 사용하는 가구 아이템. 침대 등

-functions
bool SetOccupiedCharacter(Character* new_character)
새로운 캐릭터가 해당 가구를 사용하려고 시도함. 실패시 false리턴
Character* LeaveOccupiedCharacter()
현재 가구를 사용중이던 캐릭터가 떠남. 사용하던 캐릭터를 리턴

5. EquipItem : Item
stat을 가지고, 캐릭터에 장착할 수 있는 아이템들. 처음 생성시엔 name, type만 선언되고 stat은 AddStat으로 추가해줘야함

-------------------------------------
ID 생성
GameProgrammingProject\GameProgrammingProject\CPP\BeginnerVillage 에 있는 ItemDictionary.csv파일에 아이템 목록을 채우면, 그에 맞춰서 아이디를 생성해줌

1, IDRepository
2. IDService 
type list에 타입별 id가 기록되어있고, (Material =0, Furniture =1등..) 새로운 아이디를 생성하고자 하면 SetNewID(type)을 실행하면 된다.

---------------------------------------
ItemDictionaryService
csv파일을 읽어와 아이템의 정보를 갖고있는 dictionary service
name이나(모든 아이템의 이름이 유니크 하다고 일단 가정하고 만들었음, 
Item을 생성하려면 이곳을 거쳐 생성해아한다.

예시)
Item* wood = GetGameService()->item_service->GetItemByName("wood");
FurnitureItem* simple_chair = (FurnitureItem *)GetGameService()->item_service->GetItemByName("simple_chair");

무기 전시대 설치하고 그곳에 무기 전시하기
DisplayStandItem* weapon_display_stand = (DisplayStandItem* )GetGameService()->item_service->GetItemByName("weapon_display_stand");
EquipItem* sword = (EquipItem* )GetGameService()->item_service->GetItemByName("sword");

weapon_display_stand->SetSlotItem(sword, 0);

캐릭터가 이용하는 가구 설치하고 그곳에 캐릭터 배정하기
OccupiedFurnitureItem* simple_bed = (OccupiedFurnitureItem*)GetGameService()->item_service->GetItemByName("simple_bed");
simple_bed->SetOccupiedCharacter(character);

-------------------------------------
추가해야 할 기능
csv 파일에 equipitem에 대해선 stat정보도 미리 적어두게 해, dictionary를 설정할 때 stat정보도 바로 등록되도록 하기

2021-12-03 17:12 UTC, linenive requested changes
고생하셨습니다... 확인 바랍니다...

2021-12-03 17:12 UTC, linenive commented on CPP/NativeLib/NativeLib/ItemDictionaryService.h
> +class ItemDictionaryService {
1. 질문: 이거는 아이템 데이터를 최초에 로드하면서 모든 아이템을 한 번씩 만들어놓고, 이름이나 아이템 코드로 접근해서 빼서 쓸 수 있게 하는 클래스야?
2. 제안1: 읽어보니까 Service는 아닌 것 같은데? 그냥 ItemDictionary라고하자
3. 제안2: 만약 1번 질문이 맞다면 데이터들을 static으로 가지고 있게 해서 어디서든 쓸 수 있게 하면 될것같은데?

2021-12-03 17:12 UTC, linenive commented on CPP/NativeLib/NativeLib/ItemService.h
> +class ItemService {
이 서비스는 뭘 하는 서비스야? 아직은 ItemDictionaryService의 함수를 갖다쓰는 기능밖에 없는것같은데?? 어떤 기능이 들어가는거지?

2021-12-03 17:12 UTC, linenive commented on CPP/NativeLib/NativeLib/SaleItem.h
> +class SaleItem : public Item {
이거는 클래스로 분화하면 안되지 않을까? 예를들어 이렇게 하면 Item을 상속받는 가구 같은거는 못팔게 되잖아. 팔 수 있냐 없냐는 클래스가 아니라 속성으로 해야할듯? 상속구조를 보니까 Item의 자식이 SaleItem이고 그 자식이 StatItem이던데 이런것도 구조가 이상해지는것같아

2021-12-03 17:12 UTC, linenive commented on CPP/NativeLib/NativeLib/StoreItem.h
> +
이 클래스는 설명이 없는 것 같은데 무슨 클래스야?

2021-12-04 05:26 UTC, chamomy127 commented on CPP/BeginnerVillage/.data/Item_dictionary.csv
> +﻿type,name,,,,,
와와 확인하고 수정할게

2021-12-04 17:33 UTC, linenive approved these changes
확인했습니다.

2021-12-04 17:33 UTC, linenive commented on CPP/NativeLib/NativeLib/Item.h
> +	unordered_map<string, int> par_list;
par는 너무 줄인거 아녀
```sugestion
unordered_map<string, int> param_list;
```

2021-12-04 17:33 UTC, linenive commented on CPP/BeginnerVillage/Scene/MainGame.tscn
> -[connection signal="create_character" from="." to="JanTestGDScript/TestTileCreater" method="_on_Main_create_character"]
이거 컴파일 오류날 때 종종 이렇게 날아가는뎅 이상태로 머지하면 안되니까 확인하고 복구해주라

2021-12-05 16:22 UTC, merged